import HomeCarausel from "components/carausel/carausel.comp";
import FAQ from "components/faq.comp";
import Featurepage from "components/feature.comp";
import HowitWorks from "components/howitworks.comp";
import Head from "next/head";

function Home() {
  return (
    <>
      <Head>
        <title>take your seat</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeCarausel />
      <Featurepage />
      <FAQ />
    </>
  );
}

export default Home;
